import { AnimatePresence, motion } from 'framer-motion';
import { CheckCircle, Clock, Sparkles, X, Zap } from 'lucide-react';
import { useMessageProcessor } from '../hooks/useMessageProcessor';
import { useAppStore } from '../stores/useAppStore';
import type { WebSocketMessage } from '../stores/useAppStore';
import MarkdownRenderer from './MarkdownRenderer';

const StatusIndicator = ({ message }: { message: WebSocketMessage }) => {
  const getStatusIcon = () => {
    switch (message.status) {
      case 'completed':
        return <CheckCircle className="w-4 h-4 text-blue-400" />;
      case 'started':
        return <Clock className="w-4 h-4 text-blue-400 animate-spin" />;
      default:
        return <Zap className="w-4 h-4 text-blue-400" />;
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, x: -20 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: -20 }}
      transition={{ duration: 0.3 }}
      className="flex items-center gap-2 text-sm text-gray-300 py-2 border-l-2 border-blue-500/30 pl-4"
    >
      {getStatusIcon()}
      <span className="capitalize">{message.status?.replace('_', ' ') || 'Processing'}</span>
      {message.agent && <span className="text-gray-500">• {message.agent}</span>}
    </motion.div>
  );
};

const AgentResponseCard = ({ message }: { message: WebSocketMessage }) => (
  <motion.div
    initial={{ opacity: 0, x: -20 }}
    animate={{ opacity: 1, x: 0 }}
    exit={{ opacity: 0, x: -20 }}
    className="p-4 bg-slate-900/60 backdrop-blur-sm border border-blue-500/20 rounded-lg mb-3"
  >
    <div className="flex items-center gap-2 mb-2">
      <span className="text-sm font-medium text-white capitalize">{message.status?.replace('_', ' ')}</span>
      {message.agent && <span className="text-xs text-gray-400">• {message.agent}</span>}
    </div>
    {message.result && <p className="text-sm text-gray-300">{message.result.result}</p>}
  </motion.div>
);

const FinalAnswerCard = ({ finalResult, onDismiss }: { finalResult: WebSocketMessage; onDismiss: () => void }) => (
  <motion.div
    initial={{ opacity: 0, x: 30 }}
    animate={{ opacity: 1, x: 0 }}
    transition={{ duration: 0.6 }}
    className="relative"
  >
    <motion.button
      onClick={onDismiss}
      whileHover={{ scale: 1.1 }}
      whileTap={{ scale: 0.9 }}
      className="absolute -top-2 -right-2 z-10 p-2 bg-slate-800 hover:bg-slate-700 rounded-full border border-blue-500/30 transition-colors"
    >
      <X className="w-4 h-4 text-gray-400" />
    </motion.button>

    <div className="bg-slate-900/80 backdrop-blur-xl border-2 border-blue-500/40 rounded-2xl p-6 shadow-2xl">
      <div className="flex items-start gap-3 mb-4">
        <div className="p-2 bg-blue-500/20 rounded-lg">
          <Sparkles className="w-5 h-5 text-blue-400" />
        </div>
        <div>
          <h3 className="text-lg font-bold text-white mb-1">Final Answer</h3>
          <p className="text-xs text-gray-400">Generated by {finalResult.geminiSynthesis?.model || 'AI Model'}</p>
        </div>
      </div>

      <div className="prose prose-invert max-w-none">
        <MarkdownRenderer content={finalResult.geminiSynthesis?.text || 'No response available'} />
      </div>
    </div>
  </motion.div>
);

const AgentResponsePanel = () => {
  const {
    messages,
    isLoading,
    visibleMessages,
    showFinalResult,
    setIsComplete,
    setShowFinalResult,
    clearMessages,
  } = useAppStore();

  useMessageProcessor();

  const handleDismiss = () => {
    clearMessages();
    setIsComplete(false);
    setShowFinalResult(false);
  };

  const getFinalResult = () => messages.find(msg => msg.geminiSynthesis);

  if (isLoading && messages.length === 0) {
    return (
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className="flex items-center justify-center gap-3 p-6 bg-slate-900/60 backdrop-blur-sm border border-blue-500/30 rounded-xl"
      >
        <motion.div
          className="w-5 h-5 border-2 border-blue-400 border-t-transparent rounded-full"
          animate={{ rotate: 360 }}
          transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
        />
        <span className="text-gray-300">Processing your request...</span>
      </motion.div>
    );
  }

  if (showFinalResult) {
    const finalResult = getFinalResult();
    if (!finalResult) return null;
    
    return (
      <div className="grid grid-cols-12 gap-6">
        <div className="col-span-5">
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="sticky top-6 space-y-4"
          >
            <div className="bg-slate-900/60 backdrop-blur-xl border-2 border-blue-500/30 rounded-xl p-4">
              <h3 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
                <Zap className="w-4 h-4 text-blue-400" />
                Agent Updates
              </h3>
              <div className="space-y-1 max-h-[300px] overflow-y-auto scrollbar-hide">
                <AnimatePresence>
                  {visibleMessages.map((message, index) => (
                    <StatusIndicator key={`${message.requestId}-${message.status}-${message.agent || index}`} message={message} />
                  ))}
                </AnimatePresence>
                {isLoading && (
                  <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="flex items-center gap-2 text-xs text-gray-400 py-2 border-l-2 border-blue-500/30 pl-4"
                  >
                    <motion.div
                      className="w-3 h-3 border-2 border-blue-400 border-t-transparent rounded-full"
                      animate={{ rotate: 360 }}
                      transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                    />
                    <span>Processing...</span>
                  </motion.div>
                )}
              </div>
            </div>

            {finalResult.geminiSynthesis?.individualResults && (
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="bg-slate-900/60 backdrop-blur-xl border-2 border-blue-500/30 rounded-xl p-4"
              >
                <h4 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
                  <Sparkles className="w-4 h-4 text-blue-400" />
                  Individual Agent Analysis
                </h4>
                <div className="space-y-3 max-h-[400px] overflow-y-auto scrollbar-hide">
                  {Object.entries(finalResult.geminiSynthesis.individualResults).map(([agent, result]) => (
                    <motion.div
                      key={agent}
                      initial={{ opacity: 0, x: -10 }}
                      animate={{ opacity: 1, x: 0 }}
                      className="p-3 bg-slate-800/50 rounded-lg border border-blue-500/20"
                    >
                      <div className="flex items-start gap-2">
                        <div className="w-7 h-7 bg-gradient-to-r from-blue-500 to-green-500 rounded-full flex items-center justify-center text-white text-xs font-bold flex-shrink-0">
                          {agent.charAt(0)}
                        </div>
                        <div className="flex-1">
                          <h5 className="text-white font-medium mb-1 text-sm">{agent}</h5>
                          <div className="text-gray-300 text-xs">
                            <MarkdownRenderer content={result} />
                          </div>
                        </div>
                      </div>
                    </motion.div>
                  ))}
                </div>
              </motion.div>
            )}
          </motion.div>
        </div>

        <div className="col-span-7">
          <FinalAnswerCard finalResult={finalResult} onDismiss={handleDismiss} />
        </div>
      </div>
    );
  }

  if (visibleMessages.length === 0 && !isLoading) {
    return null;
  }

  return (
    <div className="grid grid-cols-12 gap-6">
      <div className="col-span-5">
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          className="sticky top-6"
        >
          <div className="bg-slate-900/60 backdrop-blur-xl border-2 border-blue-500/30 rounded-xl p-4">
            <h3 className="text-sm font-semibold text-white mb-3 flex items-center gap-2">
              <Zap className="w-4 h-4 text-blue-400" />
              Agent Updates
            </h3>
            <div className="space-y-1 max-h-[600px] overflow-y-auto scrollbar-hide">
              <AnimatePresence>
                {visibleMessages.map((message, index) => (
                  <StatusIndicator key={`${message.requestId}-${message.status}-${message.agent || index}`} message={message} />
                ))}
              </AnimatePresence>
              {isLoading && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  className="flex items-center gap-2 text-xs text-gray-400 py-2 border-l-2 border-blue-500/30 pl-4"
                >
                  <motion.div
                    className="w-3 h-3 border-2 border-blue-400 border-t-transparent rounded-full"
                    animate={{ rotate: 360 }}
                    transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                  />
                  <span>Processing...</span>
                </motion.div>
              )}
            </div>
          </div>
        </motion.div>
      </div>

      <div className="col-span-7">
        {visibleMessages.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-3"
          >
            {visibleMessages.map((message, index) => (
              <AgentResponseCard key={`${message.requestId}-${message.status}-${message.agent || index}`} message={message} />
            ))}
          </motion.div>
        )}
      </div>
    </div>
  );
};

export default AgentResponsePanel;
